version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(go deps)[main]'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: gomod
  directory: "/"
  target-branch: "v8"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(go deps)[v8]'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: gomod
  directory: "/"
  target-branch: "v7"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(go deps)[v7]'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(gha deps)[main]'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "v8"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(gha deps)[v8]'
  groups:
    dependencies:
      patterns:
        - '*'
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "v7"
  schedule:
    interval: weekly
    day:      monday
    time:     '01:00'
    timezone: US/Pacific
  open-pull-requests-limit: 2
  commit-message:
    prefix: '(gha deps)[v7]'
  groups:
    dependencies:
      patterns:
        - '*'